Integration with Bolide
defiyield-app/defiyield-self-integrations pull request #10
Opened 2023-01-20 07:39 UTC by Scriptoz

- **Project Name**: Bolide

- **Project Website**: https://bolide.fi/

- **Description**: Integration with Bolide

- **Please check if the PR fulfills these requirements**

* [x] The projects name, twitter, URL etc have been filled out in `index.ts`
* [x] Tests for the new features have been added (for bug fixes / features)
* [x] Any required Logos are included in this PR

- **Logo**: https://invest.bolide.fi/img/BLID_token_logo_2000x2000.png

2023-01-20 22:01 UTC, not-reed requested changes
Looks great, thanks for the PR! If you could just change how the `formatUnits` is being imported in the `fetchUserPositions` calls, the rest looks good to me :+1:

2023-01-21 06:30 UTC, Scriptoz commented on apps/workshop/projects/Bolide/modules/StakingPools.ts
> +        balance: parseFloat(formatUnits(amount, blidToken.decimals)),
@not-reed Thank you for the advise! Fixed

2023-01-25 16:46 UTC, not-reed commented on apps/workshop/projects/Bolide/modules/StakingPools.ts
> +        balance: parseFloat(formatUnits(amount, blidToken.decimals)),
@Scriptoz awesome, thanks!

2023-01-26 03:21 UTC, Scriptoz commented
@not-reed Issues with linter was fixed

2023-01-26 13:16 UTC, merged