Feat: add pools module to Symbiosis finance project
defiyield-app/defiyield-self-integrations pull request #27
Opened 2023-02-07 13:48 UTC by allush

- **Project Name**:

- **Project Website**:

- **Description**: (New Project, new Feature for a project, bugfixes, etc...)

- **Please check if the PR fulfills these requirements**

* [ ] The projects name, twitter, URL etc have been filled out in `index.ts`
* [ ] Tests for the new features have been added (for bug fixes / features)
* [ ] Any required Logos are included in this PR

- **Logo**: (High res logo compatible with dark and light backgrounds)

- **Other information**: (Any farms or features left to be implemented, addresses to be used for testing, etc)

2023-02-07 13:53 UTC, allush commented
There is a problem. Tokens in new chains not show in test interface ans user's position for them not show as well.

2023-02-08 09:03 UTC, witem commented
@allush, our system doesn't support new chains. So to add support for them, we should first make some internal changes. I will discuss it with our team and give you some timelines.

2023-02-08 09:38 UTC, allush commented
> @allush, our system doesn't support new chains. So to add support for them, we should first make some internal changes. I will discuss it with our team and give you some timelines.

I can disable (comment) unsupported chains (Telos, Boba BNB, Boba Avax). Will it be ok and can you merge such PR?

2023-02-08 10:12 UTC, witem requested changes

2023-02-08 10:17 UTC, allush commented on apps/sandbox/config.ts
> +    'boba-bnb': {
Okey, I will remove all changes linked with adding new chains.

2023-02-08 10:17 UTC, allush commented on apps/workshop/projects/SymbiosisFinance/helpers/utils.ts
> +        apr = item.pools[i].apr * 100;
Got it.

2023-02-08 10:20 UTC, allush commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
It's just call to get user's positioin, not to show this chain in interface.
And it works in sandbox. Why I can't call this chain?

2023-02-08 10:24 UTC, witem commented on apps/sandbox/config.ts
> +    'boba-bnb': {
You can check the full list at https://defiyield.app/integrations:
![image](https://user-images.githubusercontent.com/1782530/217503100-8675f2d6-9d02-4e87-bf6c-2125afaf952c.png)

2023-02-08 10:29 UTC, witem commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
Because we have a different setup for sandbox and production and in production, we don't support RPC calls for this chain

2023-02-08 10:41 UTC, allush commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
Ok, understood. Hence we can't provide connector to Symbiosis liquidity yet.

I think we need to have ability to specify operational chain (where we take user's positions) and specify displayable chain(where underlying assets lie) as well. And have both in `context` object. In common, have ability to set several chains that pass to `context` object. Is it possible?

2023-02-08 10:46 UTC, witem commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
Not sure that I understand what you mean, can you give some examples in the code? And how do you expect it should be displayed on the dashboard?

2023-02-08 10:47 UTC, allush commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
Or another option: implement all methods on our backed and call it from your module.

2023-02-08 10:59 UTC, witem commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
Yes, can be like this

2023-02-08 11:04 UTC, allush commented on apps/workshop/projects/SymbiosisFinance/modules/pools.ts
> +      const provider = new ethers.providers.JsonRpcProvider(BOBA_BNB_RPC);
> Yes, can be like this
will do it.

2023-02-08 11:50 UTC, closed without merging